# Generated by Django 3.2.9 on 2021-12-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
